name: Update V2Ray Subscription
on:
  schedule:
    - cron: '*/30 * * * *'  # هر 30 دقیقه
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-subscription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # برای دسترسی به تاریخچه کامل

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pybase64

      - name: Run subscription script
        run: python generate_subscription.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Update subscription link [auto]" --allow-empty
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/tahmaseb73/v2ray-configs.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
